#!/bin/bash

# Firebase Console Quick Links
# Use these to configure your Firebase project

echo "🔥 Firebase Console Quick Links"
echo "================================"
echo ""
echo "📊 Project Overview:"
echo "https://console.firebase.google.com/project/doc-share-55636/overview"
echo ""
echo "🗄️  Firestore Database:"
echo "https://console.firebase.google.com/project/doc-share-55636/firestore"
echo ""
echo "📋 Firestore Rules:"
echo "https://console.firebase.google.com/project/doc-share-55636/firestore/rules"
echo ""
echo "💾 Storage:"
echo "https://console.firebase.google.com/project/doc-share-55636/storage"
echo ""
echo "📋 Storage Rules:"
echo "https://console.firebase.google.com/project/doc-share-55636/storage/rules"
echo ""
echo "🔐 Authentication:"
echo "https://console.firebase.google.com/project/doc-share-55636/authentication/providers"
echo ""
echo "👥 Users:"
echo "https://console.firebase.google.com/project/doc-share-55636/authentication/users"
echo ""
echo "================================"
echo ""
echo "📖 Setup Instructions:"
echo "1. Click 'Firestore Rules' link above"
echo "2. Replace all rules with test mode rules from QUICK_FIX.md"
echo "3. Click Publish"
echo "4. Click 'Storage Rules' link above"
echo "5. Replace all rules with test mode rules from QUICK_FIX.md"
echo "6. Click Publish"
echo "7. Click 'Authentication' link above"
echo "8. Enable Email/Password provider"
echo "9. Refresh dashboard: http://localhost:8000/dashboard.html"
echo ""
echo "✨ Documents will appear immediately after setup!"
